#pragma config(Motor,  port2,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveforward(){
	motor[motor1] = 127;
	motor[motor3] = -127;
}

void moveBackward(){
	motor[motor1] = -127;
	motor[motor3] = 127;
}

void moveStrafe(){
	motor[motor2] = 127;
	motor[motor4] = -127;
}

void oppositeStrafe(){
	motor[motor2] = -127;
	motor[motor4] = 127;
}

void stopPort(){
	motor[motor1] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;
	motor[motor4] = 0;
}

void rotate(int direction){
	motor[motor1] = direction * 127;
	motor[motor2] = direction * 127;
	motor[motor3] = direction * 127;
	motor[motor4] = direction * 127;
}

void diagnol(){
	motor[motor4] = 127;
	motor[motor3] = -127;
	motor[motor2] = -127;
	motor[motor1] = 127;
}

void diagnolOTHERWAY()
{
	motor[motor4] = -127;
	motor[motor3] = 127;
	motor[motor2] = 127;
	motor[motor1] = -127;
}

task DIAGNOL(){
	while(1==1){
		if(vexRT[Btn8U]){
			diagnol();
			wait1Msec(10);
			stopAllMotors();
		}
	}
}

task strafe(){
	while(1==1){
		if(vexRT[Btn7L]){
			oppositeStrafe();
			wait1Msec(10);
			stopAllMotors();
		}
		if(vexRT[Btn7R]){
			moveStrafe();
			wait1Msec(10);
			stopAllMotors();
		}
	}
}

task ward(){
	while(1==1){
		if(vexRT[Btn7U]){
			moveforward();
			wait1Msec(10);
			stopAllMotors();
		}
		if(vexRT[Btn7D]){
			moveBackward();
			wait1Msec(10);
			stopAllMotors();
		}
	}
}

task main()
{
	startTask(ward);
	startTask(strafe);
	startTask(DIAGNOL);
	while(1==1){
	//	diagnol();
	diagnolOTHERWAY();
		wait1Msec(10);
		stopAllMotors();

		if(vexRT[Btn5U]){
			rotate(1);
			wait1Msec(10);
			stopAllMotors();
		}
		if(vexRT[Btn5D]){
			rotate(-1);
			wait1Msec(10);
			stopAllMotors();
		}
	}
	moveforward();
	wait1Msec(3000);
	moveStrafe();
	wait1Msec(3000);
	stopMotor();




}
